### ISSUE TITLE
Created An Issue Tracker For Himself

### ISSUE THREAD

**Issue by Puzzlem00n** [michcioperz/tripping-octo-wookie#1]
You don't need a place for other people to tell you what you're doing wrong. You'd get more feedback if you had a place where we tell you what you're doing right.

**Comment by michcioperz** [comment]
This is meant to be something like an abuse@ mailbox. I often don't notice I said something offensive. That's what this tracker's for.
In the end, it has more sense that issue-tracker-for-life that I made once to help people keep track of my problems like "I suddenly want a 3DS".

**Comment by Puzzlem00n** [comment]
But who on earth wants to have something like that? Listen, if you don't notice you said something offensive, people can just tell you and you move on. You don't need to make a big deal out of them with a tracker.

**Comment by michcioperz** [comment]
Welp, GamerGate maybe?
